name: Docker Image CI
env:
  DCKR_IMAGE_NAME: "pizzeria_web"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/react_pizza_web:latest
  deploy_task_definition:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Delete AWS ECS Service
        uses: icalia-actions/aws-delete-ecs-service@v0.0.1
        with:
          name: AppFrontBack
          cluster: Pizza-should-work
      - name: Deploy AWS ECS Service
        uses: icalia-actions/deploy-aws-ecs-service@v0.0.1
        with:
          name: AppFrontBack
          cluster: Pizza-should-work
          template: templates/ecs/my-service.json
          desired-count: 1
          definition-template: AppBackFront.json
#          container-images: '{"my-container":"my-built-image"}'

#      - name: Deploy task definition to Amazon ECS
#        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
#        with:
#          task-definition: AppBackFront.json
#          service: AppFrontBack
#          cluster: Pizza-should-work
#          wait-for-service-stability: true

#      - name: Stop previous task definition
#        run: stop-task --cluster Pizza-should-work --task